# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [3]:
from datetime import datetime

import numpy as np
import sys


## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [752]:
py_list = [0] * 1000
arr = np.array([0] * 1000, dtype=np.int8)
sys.getsizeof(arr)

1112

c## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [748]:
arr = np.array([0.5, 0.75, 4.5, 5.62, 9.5], dtype=np.float16)
arr[[0, 2, -1]]

array([0.5, 4.5, 9.5], dtype=float16)

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [26]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array = array[[0, 1, 4, -1]]
np.sum(array)

np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [35]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [29]:
np.mean(A, axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [30]:
np.std(A, axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [43]:
np.sum(A, axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [42]:
A[[0, 1]]


array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [44]:
A[[0, 2, -1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [198]:
import time

python_time_start = time.time()
[i for i in range(1000000)]
python_time_finish = time.time()
print(python_time_finish-python_time_start)

0.08903646469116211


In [214]:
nump_time_start = time.time()
np.arange(1000000)
nump_time_finish = time.time()
print(nump_time_finish-nump_time_start)

0.009898185729980469


### Task 6.2

In [753]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0
%time unknown_signature(vector1, vector2)
result


CPU times: total: 0 ns
Wall time: 51.3 μs


0

In [463]:
def np_unknown_signature(np_vector1, np_vector2):
    return np.dot(np_vector1, np_vector2)

np_vector1 = np.array([1, 2, 3])
np_vector2 = np.array([4, 5, 6])
result = 0
%time np_unknown_signature(np_vector1, np_vector2)
result


CPU times: total: 0 ns
Wall time: 57.9 μs


0

### Task 6.3

In [478]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
%time unknown_signature(matrix1, matrix2)


CPU times: total: 0 ns
Wall time: 17.6 μs


[[5, 12], [21, 32]]

In [491]:
# write your numpy code here # Python code
def np_unknown_signature(np_matrix1, np_matrix2):
    return np_matrix1 * np_matrix2

np_matrix1 = np.array([[1, 2], [3, 4]])
np_matrix2 = np.array([[5, 6], [7, 8]])
%time np_unknown_signature(np_matrix1, np_matrix2)

CPU times: total: 0 ns
Wall time: 47.7 μs


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [533]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%time unknown_signature(lst)

CPU times: total: 0 ns
Wall time: 9.78 μs


3.0

In [544]:
def np_unknown_signature(np_array):
    return np.mean(np_array)

np_array = np.array([1, 2, 3, 4, 5], dtype=np.int8)

%time np_unknown_signature(np_array)

CPU times: total: 0 ns
Wall time: 120 μs


np.float64(3.0)

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [562]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
%time unknown_signature(lst, mask, new_value)
lst

CPU times: total: 0 ns
Wall time: 12.9 μs


[0, 2, 0, 4, 0]

In [613]:
# numpy
def np_unknown_signature(np_array, mask, new_value):
    np_array[mask] = new_value

np_array = np.array([1, 2, 3, 4, 5])
mask = [True, False, True, False, True]
new_value = 0
%time np_unknown_signature(np_array, mask, new_value)
np_array

CPU times: total: 0 ns
Wall time: 86.8 μs


array([0, 2, 0, 4, 0])

### Task 7.2

In [642]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = %time unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

CPU times: total: 0 ns
Wall time: 10.7 μs


([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [649]:
def np_unknown_signature(np_array1, np_array2):
    bitwise_complement = ~np_array1
    bitwise_and = np_array1 & np_array2
    bitwise_or = np_array1 | np_array2
    return bitwise_complement, bitwise_and, bitwise_or

np_array1 = np.array([5, 2, 7, 4, 9])
np_array2 = np.array([3, 6, 1, 8, 10])
result_bitwise_complement, result_bitwise_and, result_bitwise_or = %time np_unknown_signature(np_array1, np_array2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

CPU times: total: 0 ns
Wall time: 58.7 μs


(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [733]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = %time unknown_signature(my_list)
result_python_style

CPU times: total: 0 ns
Wall time: 122 μs


[3, 13, 11, 21]

In [740]:
def np_unknown_signature(np_array):
    mask = (np_array % 2 == 0) & ((np_array % 3 == 0) | (np_array > 10))
    return (np_array[mask] ^ 7) + 2

np_array = np.array([6, 9, 12, 14, 17, 20])
result_python_style = %time np_unknown_signature(np_array)
result_python_style

CPU times: total: 0 ns
Wall time: 404 μs


array([ 3, 13, 11, 21])